[phases.setup]
nixPkgs = ["php83", "php83Packages.composer"]

[phases.install]
cmds = ["composer install --no-dev --optimize-autoloader"]

[phases.build]
cmds = [
  "mkdir -p storage/framework/cache storage/framework/sessions storage/framework/views",
  "mkdir -p storage/logs",
  "chmod -R 777 storage bootstrap/cache"
]

[start]
cmd = "php artisan serve --host=0.0.0.0 --port=8080"