[phases.setup]
nixPkgs = ["php83", "php83Packages.composer", "nodejs"]

[phases.install]
cmds = [
  "composer install --no-dev --optimize-autoloader",
  "npm ci"
]

[phases.build]
cmds = [
  "npm run production",
  "mkdir -p storage/framework/cache storage/framework/sessions storage/framework/views",
  "mkdir -p storage/logs",
  "chmod -R 777 storage bootstrap/cache"
]

[start]
cmd = "php artisan migrate --force && php artisan serve --host=0.0.0.0 --port=$PORT"